---
title: "Oysters_deseq2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(phyloseq)
library(DESeq2)
library(tidyverse)
```

# Input samples
```{r}
ps.oysters.filename <- "/sharedspace/oysters/output/ps.oysters.withtree.rds"
ps.pre <- read_rds(ps.oysters.filename)
```

# Filter samples
```{r}
ps.pre %>% 
  subset_samples(!Original.Sample.Name %in% c("B8","C1","C2")) %>%
  subset_samples(Description %in% c("Oyster Shells on the Natural Reef","Small Oyster Shells On Farm")) %>%
  filter_taxa(function(x) sum(x > 0) > 1, TRUE) %>% #at least two samples have the ASV
  subset_taxa(Kingdom == "Bacteria") %>%
  subset_taxa(!is.na(Phylum)) %>%
  subset_taxa(Order != "Chloroplast" | is.na(Order)) -> 
  ps
ps.rel  <- transform_sample_counts(ps, function(x) x / sum(x) )
```

# DESeq2 Analysis
```{r}
dds = phyloseq_to_deseq2(ps, ~ Location)

# calculate geometric means prior to estimate size factors
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}
geoMeans = apply(counts(dds), 1, gm_mean)

dds = estimateSizeFactors(dds, geoMeans = geoMeans)
dds = DESeq(dds, fitType="local")
res = results(dds, independentFiltering = TRUE)
summary(res)
```

```{r}
alpha = 0.1

res = res[order(res$padj, na.last=NA), ]
sigtab = res[(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
rownames(sigtab) = NULL
sigtab %>% head(10)
#write.csv(sigtab,"/sharedspace/oysters/output/deseq2/resultNatvFarm.csv", row.names = TRUE, quote = FALSE)
```

# Family Plots

## Tree
```{r}
familyChoice = "Lentisphaeraceae"
ps.rel %>%
  subset_taxa(Family == familyChoice) %>% 
  plot_tree(ladderize = "left", 
            label.tips = "Genus", 
            text.size=2,
            size = "Abundance",
            color = "Location") +
  scale_color_manual(values=c("#820010", "#69DEFF"))

#ggsave(paste("~/IBIEM2020_Oysters/FamilyPlots_NaturalMore/",familyChoice,".pdf",sep=""), height =10)
```

## Boxplot
```{r}
familyChoice <- "Microtrichaceae"
ps.rel %>%
  subset_samples(Description %in% c("Oyster Shells on the Natural Reef","Small Oyster Shells On Farm")) %>%
  subset_taxa(Family == familyChoice) ->
  ps.family

ps.family%>%
  otu_table() %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column() ->
  otu_vals

ps.family %>%
  tax_table() %>%
  as("matrix") %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  select(rowname,Genus) ->
  tax_vals

ps.family %>%
  sample_data %>%
  as("matrix") %>%
  as.data.frame() %>%
  rownames_to_column(var = "name") %>%
  select(name,Location) ->
  sampleInfo_tidy

otu_vals %>%
  left_join(tax_vals,keep=FALSE) %>%
  pivot_longer(-c(rowname,Genus)) %>%
  left_join(sampleInfo_tidy)->
  otu_tidy

otu_tidy %>%
  ggplot(aes(x = Genus, y = value, color = Location)) +
  geom_boxplot(position = position_dodge(1)) +
  #geom_point(alpha=0.2) +
  geom_dotplot(aes(fill=Location),binaxis='y', stackdir='center',
                 position=position_dodge(1), dotsize = 0.5, alpha = 0.5) +
  theme_classic() +
  coord_flip() +
  labs(x = paste(familyChoice,"Genera", sep=" "),
       y = "Relative Abundance") +
  scale_fill_manual(values=c("#820010", "#69DEFF")) +
  scale_color_manual(values=c("#820010", "#69DEFF"))

#ggsave(paste("~/IBIEM2020_Oysters/FamilyPlots/",familyChoice,".pdf",sep=""))

```

```{r}
sessionInfo()
```

