---
title: "Oysters_Phangorn"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dada2)
library(DECIPHER)
library(readr)
```

```{r}
oysters.seqtab.file <- "/sharedspace/oysters/output/seqtab_nochim_rdp.rds"
output.dir <- "/sharedspace/oysters/output"
seqtabNoC <- read_rds(oysters.seqtab.file)
```

```{r}
seqs <- getSequences(seqtabNoC)
names(seqs) <- seqs # This propagates to the tip labels of the tree
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA,verbose=FALSE)
write_rds(alignment, "/sharedspace/oysters/output/decipher_alignment.rds")
```

```{r}
library(phangorn)
phangAlign <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phangAlign)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phangAlign)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
        rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)
write_rds(fitGTR, "/sharedspace/oysters/output/fitGTR.rds")
```

```{r}
sessionInfo()
```

